### ISSUE TITLE
Planning Status

### ISSUE THREAD

**Issue by magic005** [magic005/Club_Hub_Frontend#1]
# Team Club Hub
Club Hub is a social media site targeted at making extracurricular opportunities at DNHS known and accessible, and offers a way to track those you currently take part in.
Frontend Repo: (this repo)
Backend Repo: https://github.com/magic005/flocker_backend_CSP2.git
## Features to be added:
- Homepage to display "Your Clubs" & "Announcements"
- Gemini API integration for recommendations and chatting
- Chatrooms for each club
- Ability to add new clubs
- Cache user-inputted interests
- Activity recommendation system
- Member counts
### Student/Member Side
- Home Page
  -  “Your Clubs”
  -  Announcements
  -  Tasks/assignments
- Discover Page
  -  Search club DB
  -  Interests quiz
  -  Club recommendations (clubs assigned interests, match user interests to club interests to determine best fits)
  -  Gemini API integration
- Club Pages
  -  Member counts
  -  Leadership and roles
  -  Description
  -  Contact forms
- Profile Page
  -  Roles/achievements
  -  UI/profile customization
  -  User info, stats
- Chatrooms
  -  Per-club
  -  Gemini API integration (chatbots)
  -  Translate API integration
### Student/Leadership Side
- Home Page
  -  “Your Clubs”
  -  Announcements
  -  Tasks/assignments
- Club Pages
  -  Member counts
  -  Leadership and roles
  -  Description
  -  Contact forms
  -  **Management (add users, remove users)**
  -  **Initiate leadership searches** (take applications through contact forms, review relevant applicants/profiles, etc.)
  -  Create announcements & tasks/assignments
- Chatrooms
  -  Per-club
  -  Gemini API integration (chatbots)
  -  Translate API integration
  -  **Moderator access and control**
- Profile Page
  -  Roles/achievements
  -  UI/profile customization
  -  User info, stats
### Group 1: Club Management
| Name   | Link | Assignments                                                                                 |
|--------|------|---------------------------------------------------------------------------------------------|
| Jonah  |   https://github.com/luojonah/jonahluo_student2025   | User authentication and profile data, profile page functionality and UI customization, overall UI functionality with CSS and JS, cache number of members on a per-club basis, club page functionality (backend) on per-club basis                  |
| Aarav  |   https://github.com/Aarav445/Aarav_2025   | Join/leave clubs and cache clubs on a per-user basis, moderator control over user roles in each club, club page UI and functionality with CSS and JS (user side)                 |
| Gyutae |   https://github.com/GyutaeKim1/Gyutae_2025   | Add new clubs, chatrooms dynamic on per-club basis, club page UI functionality with CSS and JS, [draw.io](http://draw.io/) flowchart for full stack site functionality                               |
### Group 2: UI, User Management
| Name   | Link | Assignments                                                                                 |
|--------|------|---------------------------------------------------------------------------------------------|
| Ansh (scrum master)  |   https://github.com/magic005/AnshCSP   | Discover page UI functionality with CSS and JS, user interests cached on per-user basis, match users to clubs, home page UI and functionality with CSS and JS, Kanban board                 |
| Ethan |   https://github.com/EthanZ123/ethan_2025   | API integrations for recommendations and chatting, chatrooms pages UI and functionality with CSS and JS, , leadership search logic and functionality on leadership side                               |
***Align with CPT requirements***
# CPT Requirements
## CPT 1.1 & 1.2
- Kanban - organize and schedule tasks for group members
- SCRUM organization - clear delegation of responsibility within group
- Agile user stories - develop clear understanding of features and goals, identify **purpose** (on a separate issue)
- Issues - mark and create detailed explanations and plans for milestones and goals
- Utilization of College Board resources - use ideas from practice MCQs and videos and deeper understanding of requirements and structure
## CPT 1.3
- Functional UI - creation of user-friendly interactive UI with UX considerations and JS/CSS functionality (discover page, home page, profile page, etc.)
- Full stack development - usage of both backend and frontend to create seamless user experience and optimize features (data cached on per-user and per-club basis, with information regarding both cached in backend DBs)
- Use of previous Flocker - build upon established ideas for greater functionality and broader usage (AGK project)
- [Draw.io](http://draw.io/) - full stack flowcharts for concise understanding of frontend and backend integrations
- Comments - code can be clearly understood through brief comments and pseudocode logic
## CPT 1.4
- Backend debugging - use of Postman API in order to track backend queries for seamless full stack connection
- Frontend debugging - usage of inspect element for HTML/CSS debugging, and console logging for JS
## CPT 2
- SQLite - management of backend SQL database for storage of information and user/site data
- Image uploads - upload profile pictures and store in DB, properly linked to profiles
- Data Security - site is secure and user data is private, adhering to best practice and standards
## CPT 4
- Deployment - site is active and accessible through Github Pages domain
- DNS - understand how domain names work, with regard to networking
- HTTP and RESTful APIs - implementation of HTTP processes for backend interactions
- Security and authentication - users authenticated through passwords, secure in backend DBs
# Tasks
- [x] Ideation, determine features and potential implementations, delegate, create kanban board
- [x] Initial set up – create and initialize frontend and backend repositories
- [ ] Add pages (minimal functionality, proof of concept)
- [ ] Backend functionality (per-user and per-club databases for multiple parameters)
- [ ] UI design finalization and implementation, JS and CSS functionality per-page
- [ ] Frontend integration – “fetch” logics, API integration, frontend functionality
- [ ] Testing, final changes (edited)
